---
require:
  - rubocop-rspec

LineLength:
  Max: 130

MethodLength:
  Max: 20

Metrics/ParameterLists:
  CountKeywordArgs: false

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

EndAlignment:
  EnforcedStyleAlignWith: variable

Documentation:
  Enabled: false
